# See [Source Acceptance Tests](https://docs.airbyte.io/contributing-to-airbyte/building-new-connector/source-acceptance-tests.md)
# for more information about how to configure these tests
connector_image: airbyte/source-amazon-ads:dev
tests:
  spec:
    - spec_path: "source_amazon_ads/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
      empty_streams: ["sponsored_display_campaigns"]
      expect_records:
        path: "integration_tests/expected_records.txt"
        extra_fields: no
        exact_order: no
        extra_records: yes
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/no_profiles_catalog.json"
      empty_streams:
        [
          "sponsored_display_campaigns",
          "sponsored_display_ad_groups",
          "sponsored_display_product_ads",
          "sponsored_display_targetings",
        ]
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
